
export const NORMALIZE_MODEL = 'gemini-2.5-flash';
export const TRANSLATE_MODEL = 'gemini-2.5-flash';
export const FIX_MODEL = 'gemini-2.5-flash';

export const BATCH_SIZE = 15; // Number of SRT entries to process per API call

export const getNormalizationPrompt = (text: string): string => `
You are an expert assistant for proofreading Chinese subtitle files generated by OCR. 
Your task is to correct typos, formatting errors, and recognition mistakes.
Pay special attention to gender-specific pronouns like 他 (he) and 她 (she), which are often confused by OCR. Use the dialogue context to determine the correct pronoun. For example, if a character is referred to with female terms or is mentioned as being pregnant, ensure the pronoun is 她.
Only output the corrected Chinese text, maintaining the original meaning and structure of each line. 
Do not add any explanations, translations, or introductory text.

---

${text}
`;

export const getTranslationPrompt = (text: string): string => `
You are an expert translator fluent in both Chinese and Vietnamese, specializing in creating high-quality, natural-sounding movie subtitles. 
Translate the following Chinese text to Vietnamese.
- Preserve the tone and nuance of the original dialogue.
- Choose appropriate pronouns and honorifics based on context.
- Avoid literal, word-for-word translations that sound unnatural in Vietnamese.
- Ensure the translation flows well and is easy to read.
Only output the Vietnamese translation, maintaining the line-by-line structure.

---

${text}
`;

export const getCharacterAnalysisPrompt = (text: string): string => `
You are an AI assistant analyzing a movie script to identify characters.
Analyze the following Vietnamese subtitle dialogue. Identify all unique characters mentioned by name.
Based on context, assign a probable gender ('Nam', 'Nữ', or 'Không xác định') to each.
Output the result ONLY as a single, valid JSON object with the following structure: { "characters": [{ "name": "string", "gender": "Nam" | "Nữ" | "Không xác định" }] }.
Do not include any other text, explanations, or markdown formatting.

---

${text}
`;

export const getGenderFixPrompt = (text: string, characterJson: string): string => `
You are a Vietnamese language expert specializing in correcting movie subtitles. 
Your task is to fix gender-specific pronouns and terms of address based on a provided character list. This is a critical step to fix common AI translation errors.

Character Genders (This is the source of truth):
${characterJson}

Subtitle Text to Correct:
${text}

Instructions:
1. Review each line of the subtitle text carefully.
2. For each line, identify who is speaking or being referred to.
3. Use the Character Genders list to correct ANY incorrect pronouns (e.g., change "cô ấy" to "anh ấy" if the character is male, and vice-versa).
4. Pay close attention to contextually sensitive phrases. For example, if a character is mentioned as being pregnant, but the translation uses "anh ấy", you MUST correct it to "cô ấy" if the character is listed as female in the JSON.
5. Ensure all titles and gendered language align with the provided character list.
6. The correction must be natural and fit the context.
7. Output ONLY the corrected Vietnamese text, preserving the original line-by-line structure. Do not add explanations.
`;
